version: '3.8'

services:
  chroma:
    image: ghcr.io/chroma-core/chroma:0.4.15
    container_name: chroma
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    restart: unless-stopped
